-- MySQL Script generated by MySQL Workbench
-- 03/15/15 14:55:52
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema resume_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resume_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `resume_db` ;

-- -----------------------------------------------------
-- Table `resume_db`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resume_db`.`locations` (
  `location_id` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `zip` INT NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resume_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resume_db`.`users` (
  `user_id` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `location_id` BIGINT(100) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `location_id_idx` (`location_id` ASC),
  CONSTRAINT `user_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `resume_db`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resume_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resume_db`.`employees` (
  `employee_id` BIGINT(100) NOT NULL,
  `skillset` VARCHAR(2000) NOT NULL,
  CONSTRAINT `employee_user_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `resume_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resume_db`.`employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resume_db`.`employers` (
  `employer_id` BIGINT(100) NOT NULL,
  `company_name` VARCHAR(200) NOT NULL,
  INDEX `user_id_idx` (`employer_id` ASC),
  CONSTRAINT `employer_user_id`
    FOREIGN KEY (`employer_id`)
    REFERENCES `resume_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resume_db`.`listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resume_db`.`listings` (
  `listing_id` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `salary` BIGINT(100) NOT NULL,
  `position` VARCHAR(200) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `location_id` BIGINT(100) NOT NULL,
  `owner_id` BIGINT(100) NOT NULL,
  `skills_looking_for` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`listing_id`),
  INDEX `location_id_idx` (`location_id` ASC),
  INDEX `employer_id_idx` (`owner_id` ASC),
  CONSTRAINT `location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `resume_db`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `listing_owner_id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `resume_db`.`employers` (`employer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resume_db`.`resumes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resume_db`.`resumes` (
  `resume_id` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `author_id` BIGINT(100) NOT NULL,
  `resume` VARBINARY(1024) NOT NULL,
  PRIMARY KEY (`resume_id`),
  INDEX `author_id_idx` (`author_id` ASC),
  CONSTRAINT `author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `resume_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
